name: unittest

on:
  push:

jobs:
  unittest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        without-liburing:
        - 
        - --without-liburing
        include:
        - packages: liburing-dev
          without-liburing:

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev libgtest-dev ${{ matrix.packages }}
    - uses: actions/checkout@v4
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-asan --enable-trace ${{ matrix.without-liburing }}
    - name: make
      run: make -j$(nproc)
    - name: make test
      run: make test

  testio:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        without-liburing:
        - 
        - --without-liburing

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxhash-dev liburing-dev
    - uses: actions/checkout@v4
      with:
        path: librawstor
    - name: install librawstor
      run: |
        pushd .
        cd ./librawstor
        ./autogen.sh
        ./configure --enable-trace --disable-shared --enable-asan --disable-tests ${{ matrix.without-liburing }}
        make -j$(nproc)
        sudo make install
        popd
    - uses: actions/checkout@v4
      with:
        repository: rawstor/rawstor_ost
        path: rawstor_ost
        ref: refs/heads/main
        ssh-key: ${{ secrets.RAWSTOR_OST_TOKEN }}
    - name: (ost) install rawstor_ost
      run: |
        pushd .
        cd ./rawstor_ost
        ./autogen.sh
        ./configure --disable-shared
        make -j$(nproc)
        sudo make install
        popd
    - name: (ost) start rawstor_ost
      run: |
        mkdir /tmp/objects
        ost 8080 /tmp/objects/ &
        sleep 1
    - name: create object file,ost
      run: |
        object_uri=$(rawstor-cli create --uri file:///tmp/objects,ost://127.0.0.1:8080 --size=1)
        echo "OBJECT_URI=${object_uri}" >> $GITHUB_ENV
    - name: testio file,ost
      run: |
        rawstor-cli testio --object-uri=${OBJECT_URI} --block-size=4096 --io-depth=1 --count=10
        rawstor-cli testio --object-uri=${OBJECT_URI} --block-size=4096 --io-depth=1 --count=10 --vector-mode
    - name: create object ost,file
      run: |
        object_uri=$(rawstor-cli create --uri ost://127.0.0.1:8080,file:///tmp/objects --size=1)
        echo "OBJECT_URI=${object_uri}" >> $GITHUB_ENV
    - name: testio ost,file
      run: |
        rawstor-cli testio --object-uri=${OBJECT_URI} --block-size=4096 --io-depth=1 --count=10
        rawstor-cli testio --object-uri=${OBJECT_URI} --block-size=4096 --io-depth=1 --count=10 --vector-mode
    - name: (ost) stop rawstor_ost
      run: killall ost
